---
server:
  port: 9294

spring:
  application:
    environment: dev


# Spring Boot Actuator
management:
  server:
    port: 9294


credential-registry:
  rp-register-service-url: http://rp-register-service:9200/v1/credential-issuers
  api-key-header-id: X-API-KEY
  api-key-value: xxx

