---
server:
  port: 9294

spring:
  application:
    environment: docker


# Spring Boot Actuator
management:
  server:
    port: 9294


credential-registry:
  rp-register-service-url: http://rp-register-service:9200/v1/credential-issuers
